/**
 * AmneziaWG Architect — AmneziaWG client compatibility matrix.
 *
 * Source data: upstream amneziawg-android, amneziawg-windows, amneziawg-go,
 * AmneziaVPN desktop/mobile, community firmware packages and user reports.
 */

import type { ClientCapability } from "./types";

export const CLIENTS: Record<string, ClientCapability> = {
  "amneziawg-android": {
    id: "amneziawg-android",
    name: "AmneziaWG Android",
    platforms: ["Android 5+"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: true,
    supportsCpsTagRC: true,
    supportsCpsTagRD: true,
    supportsI1I5: true,
    maxJc: 10,
    maxS4: 32,
    knownIssues: [],
  },
  "amneziawg-ios": {
    id: "amneziawg-ios",
    name: "AmneziaWG iOS",
    platforms: ["iOS 15+"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: true,
    supportsCpsTagRC: true,
    supportsCpsTagRD: true,
    supportsI1I5: true,
    maxJc: 10,
    maxS4: 32,
    knownIssues: [],
  },
  "amneziawg-windows": {
    id: "amneziawg-windows",
    name: "AmneziaWG Windows",
    platforms: ["Windows 10+"],
    maxHValue: 2_147_483_647, // INT32_MAX
    supportsS3S4: true,
    supportsCpsTagC: false,
    supportsCpsTagRC: false,
    supportsCpsTagRD: false,
    supportsI1I5: true,
    maxJc: 10,
    maxS4: 32,
    knownIssues: ["H-value cap at INT32_MAX (issue #85)"],
  },
  "amneziavpn": {
    id: "amneziavpn",
    name: "Amnezia VPN",
    platforms: ["Android", "iOS", "Windows", "macOS", "Linux"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: true,
    supportsCpsTagRC: true,
    supportsCpsTagRD: true,
    supportsI1I5: true,
    maxJc: 10,
    maxS4: 32,
    knownIssues: [],
  },
  "wg-tunnel": {
    id: "wg-tunnel",
    name: "WG Tunnel",
    platforms: ["Android"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: false,
    supportsCpsTagRC: false,
    supportsCpsTagRD: false,
    supportsI1I5: true,
    maxJc: 10,
    maxS4: 32,
    knownIssues: [
      "Large S3/S4 may drain battery or behave inconsistently; keep S4 modest.",
    ],
  },
  "wiresock": {
    id: "wiresock",
    name: "WireSock",
    platforms: ["Windows"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: false,
    supportsCpsTagRC: false,
    supportsCpsTagRD: false,
    supportsI1I5: true,
    maxJc: 10,
    maxS4: 32,
    knownIssues: [],
  },
  "keenetic-native": {
    id: "keenetic-native",
    name: "Keenetic (native)",
    platforms: ["Keenetic OS 4.x"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: true,
    supportsCpsTagRC: true,
    supportsCpsTagRD: true,
    supportsI1I5: true,
    maxJc: 128,
    maxS4: 32,
    knownIssues: [
      "I1 sensitivity: prefer simple <r 64> or DNS mimicry profiles.",
    ],
  },
  "awg-go-legacy": {
    id: "awg-go-legacy",
    name: "amneziawg-go (legacy)",
    platforms: ["Linux", "macOS"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: false,
    supportsCpsTagRC: false,
    supportsCpsTagRD: false,
    supportsI1I5: true,
    maxJc: 128,
    maxS4: 32,
    knownIssues: ["Tag <c> is not implemented — ErrorCode 1000."],
  },
  "openwrt": {
    id: "openwrt",
    name: "OpenWRT",
    platforms: ["OpenWrt"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: true,
    supportsCpsTagRC: true,
    supportsCpsTagRD: true,
    supportsI1I5: true,
    maxJc: 128,
    maxS4: 32,
    knownIssues: [],
  },
  "asus-merlin": {
    id: "asus-merlin",
    name: "ASUS Merlin",
    platforms: ["Asuswrt-Merlin"],
    maxHValue: 4_294_967_295,
    supportsS3S4: true,
    supportsCpsTagC: true,
    supportsCpsTagRC: true,
    supportsCpsTagRD: true,
    supportsI1I5: true,
    maxJc: 128,
    maxS4: 32,
    knownIssues: [],
  },
};

export const CLIENT_IDS = Object.keys(CLIENTS);

/** Default recommended client for new users. */
export const DEFAULT_CLIENT_ID = "amneziavpn";
